services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/backend
    command: python app.py
    environment:
      - IMAGE_BASE_URL=http://imagen:8080
    ports:
      - "5001:5001"
    volumes:
      - .:/workspace
    container_name: drone_backend

  frontend:
    image: node:18
    working_dir: /workspace/frontend/mi-app
    command: npm run serve -- --host 0.0.0.0 --port 5173
    environment:
      - VUE_APP_WEBRTC_USE_STUN=true
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace
    container_name: drone_frontend

  imagen:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/backend/Gestos
    command: python imagen.py
    environment:
      - WEBRTC_USE_STUN=true
      - WEBRTC_STUN_URL=stun:stun.l.google.com:19302
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
    container_name: drone_imagen
